### ISSUE TITLE
strange instance in fig 1

### ISSUE THREAD

**Issue by ysinwell** [siquanhuang/Multi-metrics_against_backdoors_in_FL#1]
I used  distances in fig 1 and the analysis code in file `defense.py` from line 151 to line 163 as follow:
![image](https://github.com/user-attachments/assets/4f54c5e7-60ac-4a2c-9735-d9f886c76080)
However,I can't get the same scores with fig 1, though I add a sqrt function like paper.
Are there something wrong happened?

**Comment by siquanhuang** [comment]
Sorry, Figure 1 simply illustrates the framework of our method, and the values are not calculated strictly according to our algorithm. If you want to reproduce our method, you can directly deploy it in a standard federated learning training setup.

**Comment by siquanhuang** [comment]
> I used distances in fig 1 and the analysis code in file `defense.py` from line 151 to line 163 as follow: ![image](https://private-user-images.githubusercontent.com/61909754/378656640-4f54c5e7-60ac-4a2c-9735-d9f886c76080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTMyODAsIm5iZiI6MTcyOTU5Mjk4MCwicGF0aCI6Ii82MTkwOTc1NC8zNzg2NTY2NDAtNGY1NGM1ZTctNjBhYy00YTJjLTk3MzUtZDlmODg2Yzc2MDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEwMjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZTUxY2M3M2E0NDZiYjM4MjNiMDY4MjU4OTY2NDBlZmU5ZGIwM2JiZDRkNDNiYzY4NTdiYjYxNWM2YWM1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YT4U7eUS3Afi4YvMeOHdpc7O29vs68JitZ0zY47c2Q4) However,I can't get the same scores with fig 1, though I add a sqrt function like paper. Are there something wrong happened?

Sorry, Figure 1 simply illustrates the framework of our method, and the values are not calculated strictly according to our algorithm. If you want to reproduce our method, you can directly deploy it in a standard federated learning training setup.
